[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


[invariant]
runs = 512
depth = 128
fail_on_revert = false
timeout = 60

# enables storage-aware input sampling
extra_output = ["storageLayout"]

# coverage-guided invariant fuzzing
corpus_dir = "./cache/invariant-corpus/dsce"
corpus_gzip = true
corpus_min_mutations = 5
corpus_min_size = 50


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
